---
title: "Test Var Report"
author: "EDI Hackathon"
date: "June 12, 2019"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# READ IN THE DATA AND FUNCTIONS
githubrepo_path<-"~/Documents/Code/Hackathon-Central-2019/R"
#source(paste(githubrepo_path,"knb-lter-hfr.292.2.r",sep="/"))
source(paste(githubrepo_path,"knb-lter-arc.1607.10.R",sep="/"))
source(paste(githubrepo_path,"Jporter.r",sep="/"))
source(paste(githubrepo_path,"Jocelyn_functions_only.R",sep="/"))
source(paste(githubrepo_path,"AJ_functions.R",sep="/"))
```

## Data Table Report 


```{r make_report1, echo=F,warning=F,message=F, fig.height=2,fig.width=6}
library(knitr)

df<-as.data.frame(dt1)

dt2 <- HackathonFunction1(df)
rownames(dt2) <- dt2$column_name
# once on each data frame
# pandoc.table(HackathonFunction1(df),split.cells=10)
# pandoc.table(HackathonFunction2(df),split.cells=10)
print(as.data.frame(dt2))
#print(HackathonFunction1(df),n=1e4)
print(HackathonFunction2(df),n=1e4)
# intitial spatial stuff goes here  - id coordinates
```

## Variable Report
```{r make_report2, echo=F,warning=F,message=F, fig.height=2,fig.width=6}
attach(df)



for(varname in names(df)){
  var<-get(varname)
  if (is.numeric(var)){
     print(varname[1])
     xsummary<-make_numeric_variable_summary_df(var)
     print(kable(xsummary))
     #pander(xsummary)
     x<-make_numeric_histogram(df,var,varname)
     print(x)
  }
  if(is.factor(var) | is_character(var)){
    print(varname[1])
    xsummary<-make_cat_variable_summary_df(var)
    print(kable(xsummary,format="pandoc"))
    #pander(xsummary)
    x<-make_categorical_histogram(df,var,varname)
    print(x)
  }
  if (is.Date(var)) {
    print(varname[1])
    xsummary <- make_time_variable_summary_df(var)
    print(kable(xsummary,format="pandoc"))
    x<-freqclocks_forDates(df,var,varname)
    print(x)
  }
  if (is.POSIXt(var)) {
    print(varname[1])
    xsummary <- make_time_variable_summary_df(var)
    print(kable(xsummary,format="pandoc"))
    x<-freqclocks_forPOSIX(df,var,varname)
    print(x)
  }
  if(sum(xsummary$num_missing) > 0){
    print("View where missing values occur in the data")
    x<-make_missing_plot(var)
    print(x)
  }
  # spatial heatmap function for variable
}

detach(df)
```
